(()=>{"use strict";
function installCalcGuard(){const e=document.getElementById("bizHome");if(!e||e.__calcFix)return false;const d=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML");if(!d?.get||!d?.set)return false;Object.defineProperty(e,"innerHTML",{configurable:true,get(){return d.get.call(e)},set(v){const details=e.querySelector("details"),active=document.activeElement,usingCalc=!!details?.open||!!active?.closest?.("#bizHome details");if(usingCalc)return;d.set.call(e,v)}});e.__calcFix=true;return true}
function initCalcGuard(){if(!installCalcGuard()){const o=new MutationObserver(()=>{if(installCalcGuard())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}setInterval(installCalcGuard,1500)}

const KEY="chickenEggApp2V1",DOC_ID="__farm_app_2__";let remoteStamp=0,lastSent=0,writing=false,unsub=null,pendingRemote=null,syncTimer=null;
const readLocal=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return{}}};
const stamp=x=>Number(x?.updatedAt)||0;
const isEditing=()=>{const a=document.activeElement;return !!(a&&/^(INPUT|TEXTAREA|SELECT)$/.test(a.tagName));};
function note(text){let e=document.getElementById("app2SyncNote");if(!e){e=document.createElement("div");e.id="app2SyncNote";e.style.cssText="position:fixed;left:50%;top:14px;transform:translateX(-50%);z-index:99999;background:#17351f;color:#fff;padding:10px 14px;border-radius:14px;font:800 13px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 8px 25px #0005;max-width:90vw;text-align:center";document.body.appendChild(e)}e.textContent=text;clearTimeout(e._t);e._t=setTimeout(()=>e.remove(),2200)}
function applyRemote(state){if(!state||typeof state!=="object")return;const rs=stamp(state),ls=stamp(readLocal());if(rs<=ls)return;if(isEditing()){pendingRemote=state;note("New farm data received — it will update when you finish typing.");return}localStorage.setItem(KEY,JSON.stringify(state));note("Farm data updated from another device.");setTimeout(()=>location.reload(),350)}
async function waitFirebase(){for(let i=0;i<80;i++){if(window.FirestoreDB&&(window.FirebaseUser||window.FirebaseAuth?.currentUser))return true;await new Promise(r=>setTimeout(r,250))}return false}
async function startSync(){if(syncTimer)return;if(!(await waitFirebase())){console.warn("Farm App sync: Firebase/auth not ready; retrying.");setTimeout(startSync,3000);return}try{const {doc,getDoc,setDoc,onSnapshot,serverTimestamp}=await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js");const ref=doc(window.FirestoreDB,"entries",DOC_ID);const first=await getDoc(ref),local=readLocal(),ls=stamp(local);if(first.exists()){const data=first.data()||{},remote=data.farmApp2||{},rs=stamp(remote)||Number(data.updatedAt)||0;remoteStamp=rs;if(rs>ls){applyRemote(remote);return}else if(ls>rs){writing=true;await setDoc(ref,{type:"app2",farmApp2:local,updatedAt:ls,serverUpdatedAt:serverTimestamp()});remoteStamp=ls;lastSent=ls;writing=false}}else if(ls){writing=true;await setDoc(ref,{type:"app2",farmApp2:local,updatedAt:ls,serverUpdatedAt:serverTimestamp()});remoteStamp=ls;lastSent=ls;writing=false}
if(unsub)unsub();unsub=onSnapshot(ref,s=>{if(!s.exists()||writing)return;const data=s.data()||{},remote=data.farmApp2||{},rs=stamp(remote)||Number(data.updatedAt)||0;if(rs>remoteStamp)remoteStamp=rs;if(rs>stamp(readLocal()))applyRemote(remote)},e=>console.warn("Farm App live sync listener:",e));
syncTimer=setInterval(async()=>{try{if(pendingRemote&&!isEditing()){const p=pendingRemote;pendingRemote=null;applyRemote(p);return}const current=readLocal(),cs=stamp(current);if(!cs||cs<=remoteStamp||cs===lastSent||writing)return;writing=true;await setDoc(ref,{type:"app2",farmApp2:current,updatedAt:cs,serverUpdatedAt:serverTimestamp()});remoteStamp=cs;lastSent=cs;writing=false}catch(e){writing=false;console.warn("Farm App sync retry:",e)}},1500);console.log("✅ Farm App cross-device sync active")}catch(e){console.warn("Farm App sync startup failed; retrying:",e);setTimeout(startSync,3000)}}
function init(){initCalcGuard();setTimeout(startSync,500)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,700));else setTimeout(init,700);
})();