(()=>{"use strict";
function installCalcGuard(){const e=document.getElementById("bizHome");if(!e||e.__calcFix)return false;const d=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML");if(!d?.get||!d?.set)return false;Object.defineProperty(e,"innerHTML",{configurable:true,get(){return d.get.call(e)},set(v){const details=e.querySelector("details"),active=document.activeElement,usingCalc=!!details?.open||!!active?.closest?.("#bizHome details");if(usingCalc)return;d.set.call(e,v)}});e.__calcFix=true;return true}
function initCalcGuard(){if(!installCalcGuard()){const o=new MutationObserver(()=>{if(installCalcGuard())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}setInterval(installCalcGuard,1500)}

const KEY="chickenEggApp2V1",DOC_ID="farm_app_2_v1",ARRAYS=["customers","orders","expenses","flock","chores","activity"];let writing=false,unsub=null,syncTimer=null,pendingRemote=null,lastCloudStamp=0;let diag={auth:false,doc:false,error:"",cloud:null,last:"Not checked"};
const readLocal=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return{}}};
const stamp=x=>Number(x?.updatedAt)||0;
const clone=x=>JSON.parse(JSON.stringify(x||{}));
const isEditing=()=>{const a=document.activeElement;return !!(a&&/^(INPUT|TEXTAREA|SELECT)$/.test(a.tagName));};
const num=v=>Number(v)||0;
const money=v=>"$"+num(v).toFixed(2);
const expSum=a=>(Array.isArray(a)?a:[]).reduce((s,x)=>s+num(x?.amount),0);
function note(text){let e=document.getElementById("app2SyncNote");if(!e){e=document.createElement("div");e.id="app2SyncNote";e.style.cssText="position:fixed;left:50%;top:14px;transform:translateX(-50%);z-index:99999;background:#17351f;color:#fff;padding:10px 14px;border-radius:14px;font:800 13px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 8px 25px #0005;max-width:90vw;text-align:center";document.body.appendChild(e)}e.textContent=text;clearTimeout(e._t);e._t=setTimeout(()=>e.remove(),2400)}
function recTime(x){return Number(x?.updatedAt||x?.createdAt||x?.completedAt||0)}
function mergeArray(a,b){const m=new Map();[...(Array.isArray(a)?a:[]),...(Array.isArray(b)?b:[])].forEach((x,i)=>{if(!x||typeof x!=="object")return;const id=String(x.id||`legacy-${i}-${JSON.stringify(x)}`),old=m.get(id);if(!old||recTime(x)>=recTime(old))m.set(id,x)});return [...m.values()]}
function mergeObjects(a,b){return {...(a&&typeof a==="object"?a:{}),...(b&&typeof b==="object"?b:{})}}
function mergeStates(local,remote){local=clone(local);remote=clone(remote);const newer=stamp(remote)>stamp(local)?remote:local,older=newer===remote?local:remote,out={...older,...newer};ARRAYS.forEach(k=>out[k]=mergeArray(local[k],remote[k]));out.saleMeta=mergeObjects(local.saleMeta,remote.saleMeta);out.achievements=mergeObjects(local.achievements,remote.achievements);out.goals={...(local.goals||{}),...(newer.goals||{})};out.preferences={...(local.preferences||{}),...(newer.preferences||{})};out.updatedAt=Math.max(stamp(local),stamp(remote));return out}
function same(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}}
function applyLocal(state,msg){if(!state||typeof state!=="object")return false;if(isEditing()){pendingRemote=state;note("New farm data received — it will update when you finish typing.");return false}const old=readLocal();if(same(old,state))return false;localStorage.setItem(KEY,JSON.stringify(state));note(msg||"Farm data synced from another device.");setTimeout(()=>location.reload(),500);return true}
async function waitFirebase(){for(let i=0;i<120;i++){if(window.FirestoreDB&&(window.FirebaseUser||window.FirebaseAuth?.currentUser)){diag.auth=true;renderDiag();return true}await new Promise(r=>setTimeout(r,250))}diag.auth=false;throw new Error("Firebase authentication never became ready")}
function ensureDiag(){if(document.getElementById("syncDiag"))return;const hub=document.getElementById("farm2Hub");if(!hub)return;let s=document.getElementById("syncDiagCss");if(!s){s=document.createElement("style");s.id="syncDiagCss";s.textContent=`.syncdiag{margin:14px 0;padding:16px;border-radius:20px;background:rgba(255,255,255,.84);border:1px solid rgba(31,122,58,.18)}.farm2-dark .syncdiag{background:rgba(25,33,28,.9)}.syncdiag-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.syncdiag-box{padding:12px;border-radius:15px;background:rgba(31,122,58,.07)}.syncdiag-box b{display:block;font-size:20px}.syncdiag small{display:block;color:var(--muted);font-weight:750}.syncdiag-ok{color:#238a45;font-weight:900}.syncdiag-bad{color:#d34836;font-weight:900}.syncdiag-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}@media(max-width:560px){.syncdiag-actions{grid-template-columns:1fr}}`;document.head.appendChild(s)}const e=document.createElement("div");e.id="syncDiag";e.className="syncdiag";const title=hub.querySelector(".screenTitle");if(title)title.insertAdjacentElement("afterend",e);else hub.prepend(e)}
function renderDiag(){ensureDiag();const e=document.getElementById("syncDiag");if(!e)return;const l=readLocal(),c=diag.cloud||{},le=l.expenses||[],ce=c.expenses||[];e.innerHTML=`<div class="farm2-sectionHeader"><div><div class="farm2-kicker">Cloud Sync Diagnostics</div><h3>🔄 Farm App Sync</h3></div><span class="${diag.error?"syncdiag-bad":"syncdiag-ok"}">${diag.error?"ERROR":diag.auth?"CONNECTED":"WAITING"}</span></div><div class="syncdiag-grid"><div class="syncdiag-box"><small>This Device</small><b>${le.length} expenses</b><div>${money(expSum(le))}</div></div><div class="syncdiag-box"><small>Firebase Cloud</small><b>${diag.doc?ce.length+" expenses":"No document"}</b><div>${diag.doc?money(expSum(ce)):"—"}</div></div></div><small style="margin-top:10px">Auth: ${diag.auth?"signed in":"not ready"} • Cloud doc: ${diag.doc?"found":"not found"}</small><small>Last check: ${diag.last}</small>${diag.error?`<div class="syncdiag-bad" style="margin-top:8px;word-break:break-word">${String(diag.error).replace(/[<>]/g,"")}</div>`:""}<div class="syncdiag-actions"><button onclick="syncDiagPush()">⬆️ Push This Device</button><button class="secondary" onclick="syncDiagPull()">⬇️ Pull & Merge Cloud</button></div><button class="secondary" onclick="syncDiagCheck()" style="margin-top:8px">🔄 Check Sync Now</button>`}
async function getCloud(){await waitFirebase();const {doc,getDoc}=await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js");const s=await getDoc(doc(window.FirestoreDB,"entries",DOC_ID));diag.doc=s.exists();diag.cloud=s.exists()?(s.data()?.farmApp2||{}):{};diag.last=new Date().toLocaleTimeString();diag.error="";renderDiag();return diag.cloud}
window.syncDiagCheck=async()=>{try{await getCloud()}catch(e){diag.error=`${e.code||""} ${e.message||e}`.trim();diag.last=new Date().toLocaleTimeString();renderDiag()}};
window.syncDiagPush=async()=>{try{await waitFirebase();const {doc,setDoc,serverTimestamp}=await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js");const local=readLocal(),remote=await getCloud(),out=mergeStates(remote,local);out.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(out));await setDoc(doc(window.FirestoreDB,"entries",DOC_ID),{type:"app2",farmApp2:out,updatedAt:out.updatedAt,serverUpdatedAt:serverTimestamp()},{merge:true});diag.cloud=out;diag.doc=true;diag.error="";diag.last="Pushed at "+new Date().toLocaleTimeString();renderDiag();alert("This device's Farm App data was merged into Firebase.")}catch(e){diag.error=`${e.code||""} ${e.message||e}`.trim();renderDiag();alert("Push failed: "+diag.error)}};
window.syncDiagPull=async()=>{try{const remote=await getCloud(),local=readLocal(),out=mergeStates(local,remote);out.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(out));diag.error="";diag.last="Pulled at "+new Date().toLocaleTimeString();renderDiag();alert("Cloud Farm App data merged into this device. The app will reload.");setTimeout(()=>location.reload(),250)}catch(e){diag.error=`${e.code||""} ${e.message||e}`.trim();renderDiag();alert("Pull failed: "+diag.error)}};
async function startSync(){if(syncTimer)return;if(!(await waitFirebase())){setTimeout(startSync,2500);return}try{const {doc,getDoc,setDoc,onSnapshot,serverTimestamp}=await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js");const ref=doc(window.FirestoreDB,"entries",DOC_ID);
async function reconcile(remoteRaw){const local=readLocal(),remote=remoteRaw&&typeof remoteRaw==="object"?remoteRaw:{},merged=mergeStates(local,remote);diag.cloud=remote;diag.doc=true;renderDiag();const localChanged=!same(local,merged),remoteChanged=!same(remote,merged);if(localChanged){if(applyLocal(merged,"Farm data merged from your other device."))return true}if(remoteChanged&&!writing){writing=true;const out=clone(merged);out.updatedAt=Math.max(Date.now(),stamp(local)+1,stamp(remote)+1);localStorage.setItem(KEY,JSON.stringify(out));await setDoc(ref,{type:"app2",farmApp2:out,updatedAt:out.updatedAt,serverUpdatedAt:serverTimestamp()},{merge:true});lastCloudStamp=out.updatedAt;diag.cloud=out;writing=false}return false}
const first=await getDoc(ref);diag.doc=first.exists();if(first.exists()){const d=first.data()||{};diag.cloud=d.farmApp2||{};lastCloudStamp=Number(d.updatedAt)||stamp(d.farmApp2);if(await reconcile(d.farmApp2||{}))return}else{const local=readLocal();if(Object.keys(local).length){writing=true;await setDoc(ref,{type:"app2",farmApp2:local,updatedAt:stamp(local)||Date.now(),serverUpdatedAt:serverTimestamp()},{merge:true});diag.doc=true;diag.cloud=local;writing=false}}diag.last=new Date().toLocaleTimeString();renderDiag();
if(unsub)unsub();unsub=onSnapshot(ref,s=>{if(!s.exists()||writing)return;const d=s.data()||{},remote=d.farmApp2||{};diag.doc=true;diag.cloud=remote;diag.last=new Date().toLocaleTimeString();renderDiag();lastCloudStamp=Math.max(lastCloudStamp,Number(d.updatedAt)||stamp(remote));reconcile(remote).catch(e=>{diag.error=`${e.code||""} ${e.message||e}`.trim();renderDiag()})},e=>{diag.error=`${e.code||""} ${e.message||e}`.trim();renderDiag()});
syncTimer=setInterval(async()=>{try{if(pendingRemote&&!isEditing()){const p=pendingRemote;pendingRemote=null;if(applyLocal(p,"Farm data updated."))return}const snap=await getDoc(ref),d=snap.exists()?snap.data()||{}:{},remote=d.farmApp2||{};diag.doc=snap.exists();diag.cloud=remote;diag.last=new Date().toLocaleTimeString();diag.error="";renderDiag();await reconcile(remote)}catch(e){writing=false;diag.error=`${e.code||""} ${e.message||e}`.trim();diag.last=new Date().toLocaleTimeString();renderDiag()}},3000)}catch(e){writing=false;diag.error=`${e.code||""} ${e.message||e}`.trim();diag.last=new Date().toLocaleTimeString();renderDiag();setTimeout(startSync,2500)}}
function init(){initCalcGuard();ensureDiag();renderDiag();setTimeout(startSync,500);setTimeout(()=>window.syncDiagCheck(),1200);setInterval(()=>{ensureDiag();renderDiag()},2500)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,700));else setTimeout(init,700);
})();