(()=>{"use strict";
function installCalcGuard(){const e=document.getElementById("bizHome");if(!e||e.__calcFix)return false;const d=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML");if(!d?.get||!d?.set)return false;Object.defineProperty(e,"innerHTML",{configurable:true,get(){return d.get.call(e)},set(v){const details=e.querySelector("details"),active=document.activeElement,usingCalc=!!details?.open||!!active?.closest?.("#bizHome details");if(usingCalc)return;d.set.call(e,v)}});e.__calcFix=true;return true}
function initCalcGuard(){if(!installCalcGuard()){const o=new MutationObserver(()=>{if(installCalcGuard())o.disconnect()});o.observe(document.body,{childList:true,subtree:true})}setInterval(installCalcGuard,1500)}

const KEY="chickenEggApp2V1",DOC_ID="__farm_app_2__",ARRAYS=["customers","orders","expenses","flock","chores","activity"];let writing=false,unsub=null,syncTimer=null,pendingRemote=null,lastCloudStamp=0;
const readLocal=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return{}}};
const stamp=x=>Number(x?.updatedAt)||0;
const clone=x=>JSON.parse(JSON.stringify(x||{}));
const isEditing=()=>{const a=document.activeElement;return !!(a&&/^(INPUT|TEXTAREA|SELECT)$/.test(a.tagName));};
function note(text){let e=document.getElementById("app2SyncNote");if(!e){e=document.createElement("div");e.id="app2SyncNote";e.style.cssText="position:fixed;left:50%;top:14px;transform:translateX(-50%);z-index:99999;background:#17351f;color:#fff;padding:10px 14px;border-radius:14px;font:800 13px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;box-shadow:0 8px 25px #0005;max-width:90vw;text-align:center";document.body.appendChild(e)}e.textContent=text;clearTimeout(e._t);e._t=setTimeout(()=>e.remove(),2400)}
function recTime(x){return Number(x?.updatedAt||x?.createdAt||x?.completedAt||0)}
function mergeArray(a,b){const m=new Map();[...(Array.isArray(a)?a:[]),...(Array.isArray(b)?b:[])].forEach((x,i)=>{if(!x||typeof x!=="object")return;const id=String(x.id||`legacy-${i}-${JSON.stringify(x)}`),old=m.get(id);if(!old||recTime(x)>=recTime(old))m.set(id,x)});return [...m.values()]}
function mergeObjects(a,b){return {...(a&&typeof a==="object"?a:{}),...(b&&typeof b==="object"?b:{})}}
function mergeStates(local,remote){local=clone(local);remote=clone(remote);const newer=stamp(remote)>stamp(local)?remote:local,older=newer===remote?local:remote,out={...older,...newer};ARRAYS.forEach(k=>out[k]=mergeArray(local[k],remote[k]));out.saleMeta=mergeObjects(local.saleMeta,remote.saleMeta);out.achievements=mergeObjects(local.achievements,remote.achievements);out.goals={...(local.goals||{}),...(newer.goals||{})};out.preferences={...(local.preferences||{}),...(newer.preferences||{})};out.updatedAt=Math.max(stamp(local),stamp(remote));return out}
function same(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}}
function applyLocal(state,msg){if(!state||typeof state!=="object")return false;if(isEditing()){pendingRemote=state;note("New farm data received — it will update when you finish typing.");return false}const old=readLocal();if(same(old,state))return false;localStorage.setItem(KEY,JSON.stringify(state));note(msg||"Farm data synced from another device.");setTimeout(()=>location.reload(),500);return true}
async function waitFirebase(){for(let i=0;i<120;i++){if(window.FirestoreDB&&(window.FirebaseUser||window.FirebaseAuth?.currentUser))return true;await new Promise(r=>setTimeout(r,250))}return false}
async function startSync(){if(syncTimer)return;if(!(await waitFirebase())){console.warn("Farm App sync: Firebase/auth not ready; retrying.");setTimeout(startSync,2500);return}try{const {doc,getDoc,setDoc,onSnapshot,serverTimestamp}=await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js");const ref=doc(window.FirestoreDB,"entries",DOC_ID);
async function reconcile(remoteRaw){const local=readLocal(),remote=remoteRaw&&typeof remoteRaw==="object"?remoteRaw:{},merged=mergeStates(local,remote);const localChanged=!same(local,merged),remoteChanged=!same(remote,merged);if(localChanged){if(applyLocal(merged,"Farm data merged from your other device."))return true}if(remoteChanged&&!writing){writing=true;const out=clone(merged);out.updatedAt=Math.max(Date.now(),stamp(local)+1,stamp(remote)+1);localStorage.setItem(KEY,JSON.stringify(out));await setDoc(ref,{type:"app2",farmApp2:out,updatedAt:out.updatedAt,serverUpdatedAt:serverTimestamp()},{merge:true});lastCloudStamp=out.updatedAt;writing=false}return false}
const first=await getDoc(ref);if(first.exists()){const d=first.data()||{};lastCloudStamp=Number(d.updatedAt)||stamp(d.farmApp2);if(await reconcile(d.farmApp2||{}))return}else{const local=readLocal();if(Object.keys(local).length){writing=true;await setDoc(ref,{type:"app2",farmApp2:local,updatedAt:stamp(local)||Date.now(),serverUpdatedAt:serverTimestamp()},{merge:true});writing=false}}
if(unsub)unsub();unsub=onSnapshot(ref,s=>{if(!s.exists()||writing)return;const d=s.data()||{},remote=d.farmApp2||{};lastCloudStamp=Math.max(lastCloudStamp,Number(d.updatedAt)||stamp(remote));reconcile(remote).catch(e=>console.warn("Farm App reconcile:",e))},e=>console.warn("Farm App live sync listener:",e));
syncTimer=setInterval(async()=>{try{if(pendingRemote&&!isEditing()){const p=pendingRemote;pendingRemote=null;if(applyLocal(p,"Farm data updated."))return}const snap=await getDoc(ref),d=snap.exists()?snap.data()||{}:{},remote=d.farmApp2||{};await reconcile(remote)}catch(e){writing=false;console.warn("Farm App sync retry:",e)}},3000);console.log("✅ Farm App merged cross-device sync active")}catch(e){writing=false;console.warn("Farm App sync startup failed; retrying:",e);setTimeout(startSync,2500)}}
function init(){initCalcGuard();setTimeout(startSync,500)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,700));else setTimeout(init,700);
})();