(()=>{"use strict";
const K="chickenEggInventoryV2",A="chickenEggApp2V1";let queued=false,hooked=false;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},n=v=>Math.max(0,Number(v)||0),today=()=>{let d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`},id=()=>`inv-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function st(){let x=read(K,null);return x&&typeof x==="object"?{...x,dozens:n(x.dozens),packs18:n(x.packs18),loose:n(x.loose),adjustments:Array.isArray(x.adjustments)?x.adjustments:[]}:{version:2,dozens:0,packs18:3,loose:0,adjustments:[],updatedAt:0}}
const total=s=>Math.round(n(s.dozens)*12+n(s.packs18)*18+n(s.loose)),res=()=>{let a=read(A,{orders:[]});return(Array.isArray(a.orders)?a.orders:[]).filter(o=>o.status==="pending").reduce((q,o)=>q+n(o.dozen)*12+n(o.packs18)*18,0)},avail=()=>Math.max(0,total(st())-res()),pack=t=>({dozens:0,packs18:Math.floor(Math.max(0,t)/18),loose:Math.max(0,t)%18});
function save(s,delta=0,reason="Inventory adjustment",details=""){s.adjustments=Array.isArray(s.adjustments)?s.adjustments:[];if(delta||reason==="Exact inventory count")s.adjustments.unshift({id:id(),date:today(),at:Date.now(),delta,reason,details,totalAfter:total(s)});s.adjustments=s.adjustments.slice(0,100);s.updatedAt=Date.now();localStorage.setItem(K,JSON.stringify(s));renderSoon()}
function inject(){if(!document.getElementById("invCleanCss")){let x=document.createElement("style");x.id="invCleanCss";x.textContent='.inventory-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin:12px 0}.inventory-box{text-align:center;padding:14px;border-radius:18px;background:rgba(255,255,255,.68)}.inventory-box b{display:block;font-size:26px}.inventory-setGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.inventory-historyRow{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid rgba(127,127,127,.15)}@media(max-width:600px){.inventory-setGrid{grid-template-columns:1fr}}';document.head.appendChild(x)}let app=document.querySelector(".app"),nav=document.querySelector(".bottomNav");if(app&&nav&&!document.getElementById("farm2Inventory")){let w=document.createElement("div");w.innerHTML=`<section id="farm2Inventory" class="screen"><div class="screenTitle"><button class="backMini" onclick="showScreen('farm2Hub')">←</button><h2>Egg Inventory</h2></div><div id="inventorySummary"></div><div class="farm2-card"><h3>✏️ Set Exact Inventory</h3><div class="inventory-setGrid"><div><label>Dozen Cartons</label><input id="inventoryDozens" type="number" min="0"></div><div><label>18-Packs</label><input id="inventoryPacks18" type="number" min="0"></div><div><label>Loose Eggs</label><input id="inventoryLoose" type="number" min="0"></div></div><button onclick="inventorySetExact()">Save Exact Inventory</button></div><div class="farm2-card"><h3>🥚 Use / Give Away</h3><input id="inventoryAdjustQty" type="number" min="1" placeholder="How many eggs?"><button onclick="inventoryRemove('Used at home')">🍳 Used at Home</button><button onclick="inventoryRemove('Gave to family')">❤️ Gave to Family</button><button onclick="inventoryRemove('Broken / damaged')">💔 Broken / Damaged</button></div><div class="farm2-card"><h3>➕ Add Eggs</h3><input id="inventoryAddQty" type="number" min="1"><button onclick="inventoryAddEggs()">Add Eggs</button></div><div class="farm2-card"><h3>🕒 Inventory History</h3><div id="inventoryHistory"></div></div></section>`;app.insertBefore(w.firstElementChild,nav)}let g=document.querySelector("#farm2Hub .farm2-hubGrid");if(g&&!document.getElementById("inventoryHubButton")){let b=document.createElement("button");b.id="inventoryHubButton";b.className="farm2-hubButton green";b.setAttribute("onclick","showScreen('farm2Inventory')");b.innerHTML='<span class="farm2-bigEmoji">🥚</span>Inventory<small>Physical egg count</small>';g.prepend(b)}let t=document.getElementById("farm2TodayCard");if(t&&!document.getElementById("inventoryDashboardCard")){let d=document.createElement("div");d.id="inventoryDashboardCard";d.className="farm2-card";t.insertAdjacentElement("afterend",d)}}
function render(){queued=false;inject();let s=st(),on=total(s),r=res(),av=Math.max(0,on-r),sum=document.getElementById("inventorySummary");if(sum)sum.innerHTML=`<div class="inventory-grid"><div class="inventory-box"><b>${on}</b><span>On Hand</span></div><div class="inventory-box"><b>${r}</b><span>Reserved</span></div><div class="inventory-box"><b>${av}</b><span>Available</span></div></div><div class="farm2-card">${s.dozens} dozen • ${s.packs18} 18-packs • ${s.loose} loose</div>`;[["inventoryDozens",s.dozens],["inventoryPacks18",s.packs18],["inventoryLoose",s.loose]].forEach(([i,v])=>{let e=document.getElementById(i);if(e&&document.activeElement!==e)e.value=v});let h=document.getElementById("inventoryHistory");if(h)h.innerHTML=s.adjustments.length?s.adjustments.slice(0,30).map(a=>`<div class="inventory-historyRow"><span>${a.reason}<small class="farm2-subtle"> ${a.date||""}</small></span><b>${n(a.delta)>0?"+":""}${Number(a.delta)||0} 🥚</b></div>`).join(""):'<div class="farm2-empty">No inventory adjustments yet.</div>';let c=document.getElementById("inventoryDashboardCard");if(c)c.innerHTML=`<div class="farm2-sectionHeader"><div><div class="farm2-kicker">Physical Egg Inventory</div><h3>${av} eggs available</h3></div></div><div class="inventory-grid"><div class="inventory-box"><b>${on}</b><span>On Hand</span></div><div class="inventory-box"><b>${r}</b><span>Reserved</span></div><div class="inventory-box"><b>${av}</b><span>Sell / Use</span></div></div><div class="farm2-subtle">${s.dozens} dozen • ${s.packs18} 18-packs • ${s.loose} loose</div><button onclick="showScreen('farm2Inventory')">✏️ Edit Inventory</button>`}
function renderSoon(){if(queued)return;queued=true;requestAnimationFrame(render)}
window.inventorySetExact=()=>{let s=st(),old=total(s);s.dozens=n(document.getElementById("inventoryDozens")?.value);s.packs18=n(document.getElementById("inventoryPacks18")?.value);s.loose=n(document.getElementById("inventoryLoose")?.value);save(s,total(s)-old,"Exact inventory count",`${s.dozens} dozen, ${s.packs18} 18-packs, ${s.loose} loose`)};
window.inventoryRemove=reason=>{let q=Math.round(n(document.getElementById("inventoryAdjustQty")?.value));if(!q){alert("Enter how many eggs left inventory.");return}let s=st(),old=total(s),rm=Math.min(q,old);Object.assign(s,pack(old-rm));save(s,-rm,reason);let e=document.getElementById("inventoryAdjustQty");if(e)e.value=""};
window.inventoryAddEggs=()=>{let q=Math.round(n(document.getElementById("inventoryAddQty")?.value));if(!q){alert("Enter how many eggs to add.");return}let s=st();Object.assign(s,pack(total(s)+q));save(s,q,"Manual inventory add");let e=document.getElementById("inventoryAddQty");if(e)e.value=""};
function hook(){if(hooked)return;if(typeof window.showScreen!=="function"){setTimeout(hook,100);return}hooked=true;let o=window.showScreen;window.showScreen=function(){let z=o.apply(this,arguments);setTimeout(renderSoon,0);return z}}
function init(){let s=st();if(!s.updatedAt){s.updatedAt=Date.now();s.adjustments=[{id:id(),date:today(),at:Date.now(),delta:54,reason:"Starting physical inventory",totalAfter:54}];localStorage.setItem(K,JSON.stringify(s))}hook();render();window.addEventListener("farm-data-synced",e=>{if(!e.detail?.key||[K,A].includes(e.detail.key))renderSoon()});window.addEventListener("core-data-synced",renderSoon);window.addEventListener("storage",e=>{if([K,A].includes(e.key))renderSoon()});console.log("✅ Current physical inventory active")}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,80));else setTimeout(init,80)
})();
