await import("../customer-public-reader-v2.js");
const api=window.FarmPublicCustomerReaderV2;
const facts=window.CustomerChickenFactsV1?.facts?.()||[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let current=null,filter="all",factIndex=Math.abs(new Date().toISOString().slice(0,10).replace(/-/g,"").split("").reduce((s,x)=>s+Number(x),0))%(facts.length||1);
const setText=(id,v)=>{const el=$(id);if(el)el.textContent=v;};
const signed=v=>{const x=Number(v)||0;return `${x>0?"+":""}${x.toFixed(1)}%`;};
const photoHtml=bird=>bird?.photo?`<img src="${esc(bird.photo)}" alt="${esc(bird.name||"Chicken")}">`:`<span aria-hidden="true">${["Rooster","Cockerel"].includes(bird?.sex)?"🐓":"🐔"}</span>`;
function relativeTime(t){t=Number(t)||0;if(!t)return"Live farm snapshot";const sec=Math.max(0,Math.floor((Date.now()-t)/1000));if(sec<60)return"Updated less than a minute ago";const min=Math.floor(sec/60);if(min<60)return`Updated ${min} minute${min===1?"":"s"} ago`;const hr=Math.floor(min/60);if(hr<24)return`Updated ${hr} hour${hr===1?"":"s"} ago`;return`Updated ${new Date(t).toLocaleDateString(undefined,{month:"short",day:"numeric"})}`;}
function data(){if(!current?.summary)return null;return{...current.summary,flock:current.flock||[],chickenOfTheDay:current.chickenOfTheDay||null};}
function renderAvailability(d){const a=d.availability||{};setText("availableEggs",a.eggs||0);const parts=[];if(a.dozenEquivalent)parts.push(`${a.dozenEquivalent} dozen equivalent`);if(a.remainder)parts.push(`${a.remainder} extra egg${a.remainder===1?"":"s"}`);if(!parts.length)parts.push("Check back after the next collection");setText("availabilityEquivalent",parts.join(" • "));const badge=$("availabilityBadge");if(badge){badge.textContent=a.label||"Availability updating";badge.className=`availability-badge ${a.tone||""}`.trim();}setText("freshness",relativeTime(d.publishedAt||a.updatedAt));}
function nRange(lo,hi){lo=Number(lo)||0;hi=Number(hi)||0;return lo===hi?String(hi):`${lo}–${hi}`;}
function renderProduction(d){const p=d.production||{},match=d?.customerStory?.todayMatch,confidence=d?.customerStory?.confidence;if(match&&Number.isFinite(Number(match.low))&&Number.isFinite(Number(match.high))){setText("todayForecast",nRange(match.low,match.high));setText("forecastConfidence",confidence?.label||match.confidence||p.confidence||"Learning the flock");}else{setText("todayForecast",nRange(p.todayLow,p.todayHigh));setText("forecastConfidence",p.confidence||"Learning the flock");}setText("todayCollected",p.todayCollected||0);setText("weekForecast",p.predictedWeek||0);setText("monthForecast",p.predictedMonth||0);setText("forecastNote",`${p.weekCollected||0} eggs are already logged this week • current flock pace ${Number(p.dailyPace||0).toFixed(1)} eggs/day.`);}
function renderWeather(d){const w=d.weather||{};setText("weatherEmoji",w.emoji||"🌤️");setText("weatherTemp",w.temperature==null?"—":w.temperature);setText("weatherCondition",w.condition||"Weather unavailable");setText("weatherFeels",w.feelsLike==null?"":`• feels like ${w.feelsLike}°`);setText("weatherHighLow",w.high==null||w.low==null?"—":`${w.high}° / ${w.low}°`);setText("weatherRain",w.rainChance==null?"—":`${w.rainChance}%`);setText("weatherHumidity",w.humidity==null?"—":`${w.humidity}%`);}
function renderWeatherImpact(d){const w=d.weatherInsights||{},list=$("weatherImpactList");const factors=Array.isArray(w.factors)?w.factors:[];if(factors.length){setText("weatherImpactIntro","These are patterns from this farm’s own matched weather and egg logs, not a generic chicken estimate.");if(list)list.innerHTML=factors.slice(0,2).map(f=>`<div class="weather-impact-pill"><span>${esc(f.emoji)} ${esc(f.label)}</span><strong>${signed(f.effect)}</strong></div>`).join("");setText("weatherImpactNote",`Based on ${Number(w.samples)||0} matched weather/laying days.`);const note=$("weatherImpactNote");if(note)note.innerHTML=`Based on ${Number(w.samples)||0} matched weather/laying days. <a href="stats.html">See all egg stats →</a>`;}else{setText("weatherImpactIntro","The flock is still building enough matched weather and laying days before calling anything a real pattern.");if(list)list.innerHTML="";const note=$("weatherImpactNote");if(note)note.innerHTML='<a href="stats.html">Open egg stats →</a>';}}
function renderChicken(d){const bird=d.chickenOfTheDay,photo=$("chickenDayPhoto");if(!bird){setText("chickenDayName","The flock is off camera");setText("chickenDayDetails","A featured chicken will appear when profiles are available.");if(photo)photo.innerHTML="<span>🐔</span>";return;}setText("chickenDayName",bird.name);setText("chickenDayDetails",`${bird.breed} • ${bird.sex} • ${bird.age}`);if(photo)photo.innerHTML=photoHtml(bird);}
function showFact(){if(!facts.length){setText("factText","Chicken facts are getting ready.");return;}factIndex=((factIndex%facts.length)+facts.length)%facts.length;setText("factText",facts[factIndex]);}
function match(b){if(filter==="hens")return["Hen","Pullet"].includes(b.sex);if(filter==="roosters")return["Rooster","Cockerel"].includes(b.sex);return true;}
function renderFlock(d){const all=d.flock||[],shown=all.filter(match),grid=$("flockGrid"),empty=$("emptyFlock");setText("flockCount",all.length);if(!grid)return;grid.innerHTML=shown.map(b=>`<button type="button" class="bird-card" data-bird-id="${esc(b.id)}" aria-label="View ${esc(b.name)} profile"><div class="bird-photo">${photoHtml(b)}</div><span class="bird-sex">${esc(b.sex)}</span><div class="bird-body"><strong>${esc(b.name)}</strong><span>${esc(b.breed)}<br>${esc(b.age)}</span></div></button>`).join("");if(empty)empty.hidden=shown.length>0;grid.querySelectorAll("[data-bird-id]").forEach(btn=>btn.addEventListener("click",()=>openProfile(btn.dataset.birdId)));}
function openProfile(id){const d=data(),bird=d?.flock?.find(b=>String(b.id)===String(id));if(!bird)return;const modal=$("profileModal"),photo=$("profilePhoto"),factsBox=$("profileFacts");if(photo)photo.innerHTML=photoHtml(bird);setText("profileName",bird.name);if(factsBox)factsBox.innerHTML=`<div><span>Breed</span><strong>${esc(bird.breed)}</strong></div><div><span>Sex</span><strong>${esc(bird.sex)}</strong></div><div><span>Age</span><strong>${esc(bird.age)}</strong></div><div><span>Hatch date</span><strong>${esc(bird.hatchDate||"Not listed")}</strong></div>`;if(modal){modal.hidden=false;document.body.style.overflow="hidden";modal.querySelector(".modal-close")?.focus();}}
function closeProfile(){const modal=$("profileModal");if(modal)modal.hidden=true;document.body.style.overflow="";}
function render(value){current=value||current;const d=data(),missing=$("missingData"),status=$("publicStatus");if(!d){if(missing)missing.hidden=false;if(status){status.textContent="The live customer snapshot is not published yet.";status.classList.add("error");}return;}if(missing)missing.hidden=true;if(status){status.textContent="Live customer view • updates automatically when the farm publishes a change";status.classList.remove("error");}setText("farmName",d.farm.name);setText("farmLocation",d.farm.location);setText("footerFarmName",d.farm.name);document.title=`${d.farm.name} — Farm View`;renderAvailability(d);renderProduction(d);renderWeather(d);renderWeatherImpact(d);renderChicken(d);showFact();renderFlock(d);window.dispatchEvent(new CustomEvent("customer-view-rendered",{detail:{publicVersion:Number(d.publicVersion)||0,at:Date.now()}}));}
$("nextFact")?.addEventListener("click",()=>{factIndex++;showFact();});document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{filter=btn.dataset.filter||"all";document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===btn));const d=data();if(d)renderFlock(d);}));document.querySelectorAll("[data-close-profile]").forEach(x=>x.addEventListener("click",closeProfile));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeProfile();});
window.CustomerViewPublic={version:3,getData:data,getFilter:()=>filter,openProfile,closeProfile};
try{api.subscribe(render,()=>render(null));const initial=await api.load();render(initial);}catch{render(null);}
await import("./customer-delight-v1.js?v=20260824-2010");
